import Link from "next/link";
import Image from "next/image";

export default function PrivacyPolicyPage() {
  return (
    <main style={styles.page}>
      <div style={styles.card}>
        <div style={styles.brand}>
          <Image
            src="/logo.png"
            alt="RROI logo"
            width={96}
            height={96}
            priority
          />
          <h1 style={styles.h1}>Privacy Policy</h1>
          <p style={styles.tagline}>Rapid Response Online Information (RROI)</p>
        </div>

        <section style={styles.section}>
          <h2 style={styles.h2}>1. Introduction</h2>
          <p style={styles.p}>
            Rapid Response Online Information (“RROI”, “we”, “us”, or “our”) respects
            your privacy and is committed to protecting personal information in
            accordance with the Protection of Personal Information Act, 2013
            (“POPIA”) and other applicable laws of South Africa.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>2. Information We Collect</h2>
          <p style={styles.p}>
            We may collect and store personal information provided directly by users,
            including but not limited to:
          </p>
          <ul style={styles.ul}>
            <li>Email address and account credentials</li>
            <li>Emergency contact details</li>
            <li>Medical or emergency-related information voluntarily provided by the user</li>
            <li>Subscription and billing status</li>
          </ul>
          <p style={styles.p}>
            Users are responsible for ensuring that any information provided is accurate
            and up to date.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>3. How Information Is Used</h2>
          <p style={styles.p}>
            Personal information is used solely for the purpose of providing and
            operating the RROI service, including:
          </p>
          <ul style={styles.ul}>
            <li>Creating and managing user accounts</li>
            <li>Displaying emergency information via QR code access</li>
            <li>Managing subscriptions and payments</li>
            <li>Communicating service-related notices</li>
          </ul>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>4. QR Code Access</h2>
          <p style={styles.p}>
            QR codes generated by RROI allow access to a user’s public emergency profile.
            Anyone with access to the QR code may be able to view the information that
            the user has chosen to make publicly accessible.
          </p>
          <p style={styles.p}>
            Users acknowledge and accept this risk and remain responsible for deciding
            what information is included in their profile.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>5. Data Storage & Security</h2>
          <p style={styles.p}>
            RROI takes reasonable technical and organisational measures to protect
            personal information against loss, misuse, unauthorised access, or
            disclosure.
          </p>
          <p style={styles.p}>
            However, no system can be guaranteed to be completely secure, and RROI
            cannot guarantee absolute security of personal information.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>6. Data Sharing</h2>
          <p style={styles.p}>
            RROI does not sell or rent personal information to third parties.
          </p>
          <p style={styles.p}>
            Information may be shared only where required to operate the service
            (for example, payment processing) or where required by law.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>7. Data Retention</h2>
          <p style={styles.p}>
            Personal information is retained only for as long as necessary to provide
            the service or to comply with legal obligations.
          </p>
          <p style={styles.p}>
            Users may request deletion of their profile, subject to legal or operational
            requirements.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>8. User Rights</h2>
          <p style={styles.p}>
            Users have the right to access, correct, or request deletion of their personal
            information, subject to applicable law.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>9. Changes to This Policy</h2>
          <p style={styles.p}>
            RROI may update this Privacy Policy from time to time. Continued use of the
            service constitutes acceptance of any updated policy.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>10. Contact</h2>
          <p style={styles.p}>
            For privacy-related questions or requests, please contact RROI through the
            official contact channels provided on the website.
          </p>
        </section>

        <Link href="/" style={styles.backLink}>
          ← Back to home
        </Link>
      </div>
    </main>
  );
}

const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: "100vh",
    display: "flex",
    justifyContent: "center",
    padding: 16,
    background: "#FFFFFF",
    color: "#0F172A",
    fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
  },
  card: {
    width: "100%",
    maxWidth: 800,
    border: "1px solid #E5E7EB",
    borderRadius: 16,
    padding: 24,
    background: "#FFFFFF",
  },
  brand: {
    textAlign: "center",
    marginBottom: 28,
  },
  h1: {
    fontSize: 28,
    fontWeight: 900,
    margin: "8px 0 4px",
  },
  tagline: {
    fontSize: 14,
    fontWeight: 700,
    opacity: 0.85,
    margin: 0,
  },
  section: {
    marginBottom: 18,
  },
  h2: {
    fontSize: 18,
    fontWeight: 800,
    marginBottom: 6,
  },
  p: {
    margin: "0 0 8px",
    lineHeight: 1.6,
    opacity: 0.95,
  },
  ul: {
    margin: "6px 0 8px 18px",
    lineHeight: 1.6,
    opacity: 0.95,
  },
  backLink: {
    marginTop: 16,
    display: "inline-block",
    textDecoration: "none",
    color: "#157A55",
    fontWeight: 800,
  },
};
